// src/reasoning.ts
import type Anthropic from "@anthropic-ai/sdk";
import type { ContextPack } from "./summarizer.js";

export const REQUIRED_HEADINGS = [
  "1. System Summary",
  "2. Top 5 Architectural Risks",
  "3. Production Failure Scenarios",
  "4. Refactor Plan (step-by-step)",
  "5. Senior Engineer Verdict",
];

export function validateReportSections(text: string): boolean {
  const lowerText = text.toLowerCase();
  return REQUIRED_HEADINGS.every((heading) => lowerText.includes(heading.toLowerCase()));
}

export const ABSENCE_CLAIM_RULE = `- Never claim a file or system "lacks," "is missing," "has no evidence of," or
  "does not have" something (tests, error handling, a guard clause, validation,
  a lock, etc.) unless the Context Pack gives you a concrete way to check it:
  - For test coverage specifically: each top-risk file has a \`hasTests\` boolean.
    Only state a file has no tests if \`hasTests\` is present and false. If a file
    is not in \`topRiskFiles\` at all, you have no test-coverage information about
    it — do not claim it lacks tests.
  - For anything else (error handling, locks, validation, duplicate logic, etc.):
    only claim absence if the file's full \`source\` is included in the Context
    Pack and you have actually read it looking for that thing.
  - If you cannot verify presence or absence because the relevant file's source
    or fields are not in the Context Pack, say "insufficient visibility" instead
    of asserting absence. A claim of absence without a verifiable basis is a
    fabrication, not a finding.`;

const SYSTEM_PROMPT = `You are a Staff Engineer evaluating a codebase's architecture.
You will be given a Context Pack: a system summary, top-risk files with metrics,
full source code, and a \`hasTests\` flag, a compressed dependency graph snapshot,
and (if the repo is large) cluster-level aggregates instead of per-file detail.

Rules:
- Only reason from facts present in the Context Pack. Never invent files, functions,
  dependencies, or relationships not present in the data given to you.
${ABSENCE_CLAIM_RULE}
- Always respond with exactly these five sections, in this order, using these
  exact headings:
1. System Summary
2. Top 5 Architectural Risks
3. Production Failure Scenarios
4. Refactor Plan (step-by-step)
5. Senior Engineer Verdict
Do not add, omit, or reorder sections.

Section 4 formatting rule — each step MUST follow this exact format:

**Step N: [what this step does]**
File: \`path/to/file.ts\`
> **Paste this into Claude Code:**
> [A self-contained imperative instruction an AI coding agent can execute without any other context. Include: the file path, the specific function or section to change, exactly what to change and why, and the acceptance criterion. Do not write prose — write a direct agent instruction. Example: "In \`src/metrics.ts\`, in the \`computeDependencyDepth\` function, replace the recursive \`depthOf\` DFS with an iterative Kahn's algorithm so that repos with 10,000+ import chains don't crash with a stack overflow. The function should return the same depth values as before for acyclic graphs, and return 0 for all nodes in a cycle."]

Every step needs a File and a paste-ready agent prompt. No vague steps like "refactor X for clarity" — each must be specific enough that an engineer could hand it to Claude Code and get a correct implementation without reading anything else.`;

function extractTextBlock(response: Anthropic.Messages.Message): string {
  const textBlock = response.content.find((block) => block.type === "text");
  return textBlock && "text" in textBlock ? textBlock.text : "";
}

export async function generateReport(
  client: Anthropic,
  pack: ContextPack
): Promise<string> {
  const response = await client.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 4096,
    system: SYSTEM_PROMPT,
    messages: [{ role: "user", content: JSON.stringify(pack, null, 2) }],
  });

  const text = extractTextBlock(response);

  if (!validateReportSections(text)) {
    throw new Error(
      `Claude response is missing required sections. Raw response:\n${text}`
    );
  }

  return text;
}

const MIN_SUMMARY_LENGTH = 100;

const SIMPLIFIED_SUMMARY_SYSTEM_PROMPT = `You are translating a technical software architecture report into a polished, non-technical summary for a founder, product manager, or investor evaluating the team and product — not the code.

Output format — use EXACTLY this markdown structure:

# [One-line name or description of the system, inferred from the report]

*Architecture Report  ·  Generated by ARCHIE*

---

## What This System Does

[2-3 sentences. Plain English. What does this software do and who uses it? No jargon.]

## What's Working Well

[2-4 bullet points. Genuine strengths: stability signals, good structure, things a non-technical reader would find reassuring. Be honest — don't invent positives if the report doesn't support them.]

## The 2-3 Things Most Worth Watching

[2-3 named risks, each as a short bold heading followed by 2-3 sentences. Focus on business impact: what could go wrong for users, the product, or the company — not what could go wrong in a function. No file names, no line numbers, no technical metrics.]

## Bottom Line

[3-5 sentences. Overall verdict on the codebase's health and readiness. Is this a solid foundation or does it need significant work before scaling? What is the single most important thing the team should address first? End on a clear, direct recommendation.]

Rules:
- No jargon, no file paths, no line numbers, no complexity scores or other code-level metrics.
- Focus on business-level risk and impact throughout.
- Readable in under two minutes.
- Base everything on the technical report given to you. Do not invent details not present in it.
- Every section heading must appear exactly as shown above.`;

export async function generateSimplifiedSummary(
  client: Anthropic,
  technicalReport: string
): Promise<string> {
  const response = await client.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 2048,
    system: SIMPLIFIED_SUMMARY_SYSTEM_PROMPT,
    messages: [{ role: "user", content: technicalReport }],
  });

  const text = extractTextBlock(response);

  if (text.trim().length < MIN_SUMMARY_LENGTH) {
    throw new Error(
      `Simplified summary response is too short (${text.trim().length} chars, expected at least ${MIN_SUMMARY_LENGTH}). Raw response:\n${text}`
    );
  }

  return text;
}
